### ISSUE TITLE
【报错】无法获取消息

### ISSUE THREAD

**Issue by Agnes4m** [Special-Week/nonebot_plugin_BitTorrent#1]
python3.9.12，nonebot2=2.0.0b4
nonebot_adapter_onebot = 2.1.0
bs4=0.0.1
httpx =0.23.0
asyncio =3.4.3
第一次搜索会报错上面那个，之后都是下面那个报错
以尝试更换n次cookie，也尝试更换user-agent均无用，中间空的那行是最后print，log大法也没有任何异常。
![image](https://user-images.githubusercontent.com/70925546/177122944-aea9b7ec-29e6-447e-9677-8a89da85ffa9.png)

终端显示
```
07-04 17:18:04 [SUCCESS] nonebot | ONEBOT V11 3458139180 | [message.group.normal]: Message -849076481 from 735803792@[群:1040674922] "磁力搜索 葫芦娃"
07-04 17:18:04 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_BitTorrent, type=message, priority=10, temp=False>

07-04 17:18:59 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_BitTorrent, type=message, priority=10, temp=False> running complete
```

**Comment by Special-Week** [comment]
![image](https://user-images.githubusercontent.com/87489040/177149054-369587b4-54d5-47d1-b6a7-6ec7a8c56e3b.png)
![image](https://user-images.githubusercontent.com/87489040/177149280-15a01d74-ac43-4765-83be-6014eff3410a.png)
![image](https://user-images.githubusercontent.com/87489040/177149331-635600ce-478e-4576-abc4-be6788e2bbbb.png)
我尽力模拟了

**Comment by Agnes4m** [comment]
解决惹，用的百度源然后无法ping baidu.com)

**Comment by Agnes4m** [comment]
又出现这个问题了惹，这次Ping都没问题呜呜
和之前的区别只在于nonebot_adapter_onebot = 2.1.1

![image](https://user-images.githubusercontent.com/70925546/179663563-8ee464af-183a-495b-8fd9-596ce7412959.png)
