### ISSUE TITLE
获取cookie失败, 下面是错误信息: FinishedException()

### ISSUE THREAD

**Issue by xi-yue-233** [Special-Week/nonebot_plugin_BitTorrent#11]
![S}VYQI%Z7N{S53G{PUJ5IMS](https://user-images.githubusercontent.com/58218656/232030541-0c12edc7-b15d-4a57-b723-1155359e9487.png)

**Comment by Special-Week** [comment]
网站好像爬取返回的内容加了个base64, 我看看能不能解决

**Comment by Special-Week** [comment]
已修复并且上传了pypi, 目前版本0.0.7

**Comment by xi-yue-233** [comment]
应该没问题了
