### ISSUE TITLE
返回无结果

### ISSUE THREAD

**Issue by TsukasaYahane** [Special-Week/nonebot_plugin_BitTorrent#12]
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121178437/22917bda-7d90-46d7-ac2e-048cd8691851)
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121178437/70894a49-ed01-45de-a546-cd34f4277658)
如图，重置cookie和插件环境依旧报错

**Comment by Special-Week** [comment]
他们网站结构可能改了, 有空我再改一下

**Comment by Special-Week** [comment]
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/23614817-33e1-4033-a03b-50297235c324)
已修复

**Comment by Special-Week** [comment]
我已经修复了, 但您这边一直没消息, 我先close了
