### ISSUE TITLE
搜索失败, 下面是错误信息:

### ISSUE THREAD

**Issue by voloemm** [Special-Week/nonebot_plugin_BitTorrent#14]
搜索失败, 下面是错误信息:
TypeError("'<' not supported between instances of 'str' and 'int'")

**Comment by Special-Week** [comment]
是最新的插件吗？

**Comment by voloemm** [comment]
是最新的，刚才pip uninstall了又重新下了一遍还是这样

**Comment by Special-Week** [comment]
有没有复现步骤
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/d13c028e-1e4a-43c2-831e-b6fa5fcec7fa)
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/f7b137e4-6017-4a17-97d5-00cdf1cfb3ea)
我这边测试都是正常的

**Comment by Special-Week** [comment]
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/069beab8-d4be-4319-b659-90f15dce91cf)
你再确定一下是最新的, 版本号0.0.13

**Comment by Special-Week** [comment]
我猜测一下, 你env的magnet_max_num你可能配置错了, 
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/69745294-0650-45d4-9c0e-f4eb5db47b88)
我这边测试, 本来是int的东西, 你强行填了string才会出现你这个错误
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/0aa7263b-2ae8-4fb4-a8ed-be0c46a8bbd3)

**Comment by voloemm** [comment]
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/141230164/2b7d102c-c2e7-4430-a817-cca663abc185)
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/141230164/261dbeaf-78f9-4592-9898-9813215d6659)
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/141230164/38485334-3505-4ec4-ae6b-b47c129b527e)

**Comment by Special-Week** [comment]
你后面没打注释啊，你这一行都解析成字符串了

**Comment by voloemm** [comment]
哦草我也是刚看见（

**Comment by voloemm** [comment]
对不起打扰了打扰了😥😥😥
