### ISSUE TITLE
使用shamrock协议时使用插件会出现与框架断联

### ISSUE THREAD

**Issue by echo-xianyu** [Special-Week/nonebot_plugin_BitTorrent#15]
![da8e8efb454e43c23c4cd5f559de2812](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121144452/9c447d18-726d-41be-809d-1332365e6f2a)
<img width="642" alt="11dc8fe60329c3bf01ec478651f37750" src="https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121144452/d7a85144-440e-4081-9456-b0cab0caa0d7">
![5c307f2fd606dc1bb66dba561df9da05](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121144452/3f76aedc-04c6-4830-9745-ee3cfb61ea9a)
<img width="649" alt="a3643867cabc3b49e4845446bfdd25af" src="https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/121144452/9bb30ac6-6975-4831-b4cc-a2a77561568d">
复现方法：在使用shamrock协议时发送指令使用此插件

**Comment by Special-Week** [comment]
看上去像是shamrock(这东西我还没用过)未实现send_group_forward_msg(合并转发)的问题
![image](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/03c65962-30ba-4d88-9072-8c9fc95bc259)
我这样改了一下, 你更新试试看

**Comment by echo-xianyu** [comment]
> 看上去像是shamrock(这东西我还没用过)未实现send_group_forward_msg(合并转发)的问题 ![image](https://user-images.githubusercontent.com/87489040/283461332-03c65962-30ba-4d88-9072-8c9fc95bc259.png) 我这样改了一下, 你更新试试看

还是有同样的bug，运行时会直接失去反向WS连接，
但是消息是可以正常发出来了
不知道是不是我的设置问题

**Comment by Special-Week** [comment]
我重新按照标准挫了一下node, 但是我对比了一下OpenShamrock和gocqhttp的文档, 发现gocqhttp有额外需要一个uin参数(而且还不可省略), 我不太确定Shamrock会不会因为这个多余的参数而出现问题, 你更新试试看
![7f27f4b974dad10ef641b2a147108bdb](https://github.com/Special-Week/nonebot_plugin_BitTorrent/assets/87489040/80860c66-ea0d-4893-838d-c7af3507f96d)

不行的话只能取消合并转发形式输出消息, 换成直接输出文本了

**Comment by Special-Week** [comment]
我又修正了, 我尝试获取ws连接的User-Agent来区分cqhttp与Shamrock以构造不同的消息, 我想应该是搓好了(希望是)

**Comment by echo-xianyu** [comment]
> 我又修正了, 我尝试获取ws连接的User-Agent来区分cqhttp与Shamrock以构造不同的消息, 我想应该是搓好了(希望是)

问题已经解决，十分感谢
