### ISSUE TITLE
推荐一个磁力搜索

### ISSUE THREAD

**Issue by XingNian-www** [Special-Week/nonebot_plugin_BitTorrent#2]
[nyaa.si 主要是动漫](https://nyaa.si/) 跟 [子域名 主要是涩涩](https://sukebei.nyaa.si/)
不需要cookie 而且质量比较好(

**Comment by Special-Week** [comment]
不过你这个貌似需要科学上网

**Comment by XingNian-www** [comment]
> 不过你这个貌似需要科学上网

科学对于用Bot的应该是必备项吧
主要是好用(
有时候打开还挺浪费时间的
