### ISSUE TITLE
磁力猫的cookie与user-agent可能都需重新设置

### ISSUE THREAD

**Issue by KarasumaChitos3** [Special-Week/nonebot_plugin_BitTorrent#4]
照最开始的建议只修改cookie并不生效，仍然会有验证的界面，后面观察了下请求头，我把原来的
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
改成了我的
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.50
这样就生效了能够正常访问页面了

**Comment by Special-Week** [comment]
好的, 收到
