### ISSUE TITLE
cookie变更导致失效

### ISSUE THREAD

**Issue by MomentQYC** [Special-Week/nonebot_plugin_BitTorrent#8]
磁力猫cookie格式变更了，现在直接填会无法使用

**Comment by Special-Week** [comment]
自己填呢
![image](https://user-images.githubusercontent.com/87489040/217589770-2c6b678f-8e15-4bb1-9e48-b09a1e227fd2.png)

**Comment by MomentQYC** [comment]
> 自己填呢 ![image](https://user-images.githubusercontent.com/87489040/217589770-2c6b678f-8e15-4bb1-9e48-b09a1e227fd2.png)

我获取的只有一个test的，浏览器插件也只有这一个
然后就一直没法用

**Comment by Special-Week** [comment]
好像他的cookie现在会认ip的样子, 我本机拿到的cookie服务器用不了, 服务器拿的本机用不了

**Comment by Special-Week** [comment]
> 好像他的cookie现在会认ip的样子, 我本机拿到的cookie服务器用不了, 服务器拿的本机用不了

![image](https://user-images.githubusercontent.com/87489040/217598434-d336c4d5-437d-4031-b835-7b773f261b90.png)

**Comment by MomentQYC** [comment]
确认了，是和IP绑定的，用ss临时解决的问题
感谢解答（感觉可以留着给后面的人看是什么原因）

**Comment by Ikaros-521** [comment]
Linux
`curl -i -X POST -H "Content-Type: application/x-www-form-urlencoded" -d "act=challenge" https://clm9.me/ | grep "Set-Cookie" | awk -F "Set-Cookie: " '{print $2}' | awk -F ";" '{print $1}'`
![image](https://user-images.githubusercontent.com/40910637/218267891-5625e5b1-81f8-4760-804c-dd1f0576bc55.png)

感觉可以集成一下

**Comment by Ikaros-521** [comment]
[https://github.com/Special-Week/nonebot_plugin_BitTorrent/pull/9](https://github.com/Special-Week/nonebot_plugin_BitTorrent/pull/9)
修了修

**Comment by Special-Week** [comment]
有大佬pr了自动获取cookie, 不用自己填了, 所以这里我先close了
